<!-- BEGIN -->
@import gg.jte.Content

@param Content content

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
<p>
    <a href="/">Главная</a>
    <a href="/users">Пользователи</a>
</p>
${content}
<footer>
    <a href="https://github.com/Obyrif">Мой профиль на GitHub</a>
</footer>
</body>
</html>
<!-- END -->
